drhtesting/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('playground.urls')),
    path('admin/', admin.site.urls),
    #path('employees/', include('playground.urls'))
]

playground/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('employees/', views.employees_list, name='employees')
]

playground/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    POSTIONS_WORKER = 'W'
    POSTIONS_CASHER = 'C'
    POSTIONS_CLEANER = 'N'
    
    POSTIONS_CHOICES = [
        (POSTIONS_WORKER, 'Worker'),
        (POSTIONS_CASHER, 'Casher'),
        (POSTIONS_CLEANER,'Cleaner')]
    
    GENDER_MALE = 'M'
    GENDER_FEMALE = 'F'
    
    GENDER_CHOICES = [
        (GENDER_MALE, 'Male'),
        (GENDER_FEMALE, 'Female')
    ]
    name = models.CharField(max_length=255)
    age = models.DateField(null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default=GENDER_MALE)
    email = models.EmailField(unique=True)
    position = models.CharField(max_length=1, choices=POSTIONS_CHOICES, default='W')
    salary = models.CharField(max_length=10)
    

playground/views.py
from django.shortcuts import render
from playground.models import *


# Create your views here.

def index_view(request):
    return render(request, 'playground/index.html')
def employees_list(request):
    employee = Employee.objects.all()
    return render(request, 'playground/employees.html', {'obj': employee})

playground/templates/playground/employees.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "styles.css" %}">
    <title>Employees</title>
</head>
<body>
<dev class="home-page">
    <ul>
        <h1>EMPLOYEES</h1>
        {% for employees in obj %}
            <ul class="person-tab">
                <li>{{ employees.name.capitalize }}</li>
                <li>{{ employees.get_gender_display }}</li>
                <li>{{ employees.age }}</li>
                <li>{{ employees.salary }}</li>
                <li>{{ employees.get_position_display }}</li>
            </ul>
        {% endfor %}
    </ul>
</dev>

</body>
</html>

playground/templates/playground/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static "index_styles.css" %}">
</head>
<body>

    <dev class="navbar">
        <ul class="navbar-links">
            <li><a href="http://localhost:8000">Home</a></li>
            <li><a href="http://localhost:8000/admin">Admin</a></li>
            <li><a href="http://localhost:8000/employees">Employees</a></li>
        </ul>
    </dev>
    <div class="body-style">
        <p>This is the home page</p>

    </div>


</body>
</html>